const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Adds `use_modular_headers!` to the generated iOS Podfile.
//
// @react-native-google-signin/google-signin pulls in the Swift pod
// AppCheckCore, which depends on the non-modular Obj-C pods GoogleUtilities
// and RecaptchaInterop. With CocoaPods' default static-library linkage a Swift
// pod cannot import non-modular pods, so pod install fails with:
//   "The Swift pod `AppCheckCore` depends upon `GoogleUtilities` and
//    `RecaptchaInterop`, which do not define modules."
// Enabling modular headers globally makes every pod generate a module map,
// which resolves the error. The Podfile is regenerated by prebuild on every
// build, so this must be applied as a config plugin rather than edited in place.
module.exports = function withModularHeaders(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfilePath, 'utf8');
      if (!contents.includes('use_modular_headers!')) {
        contents = contents.replace(
          /^(platform :ios.*\n)/m,
          `$1use_modular_headers!\n`,
        );
        fs.writeFileSync(podfilePath, contents);
      }
      return cfg;
    },
  ]);
};
