// Adds a missing PUBLIC root CA to Android's trust anchors, for WebView only.
//
// WHY THIS EXISTS. Albertsons' identity host, ciam.albertsons.com, chains to
// "Sectigo Public Server Authentication Root R46". Chrome trusts it because
// Chrome ships its own root store. Android System WebView does NOT — it defers
// to the platform trust store, and on a Pixel 6 running Android 13 that root is
// present only under /apex/com.android.conscrypt/cacerts and is not what the
// verifier consults. The result, straight out of logcat:
//
//   E chromium: handshake failed; SSL error code 1, net_error -202
//   W RNCWebViewClient: Resource blocked from loading due to SSL error.
//                       Blocked URL: https://ciam.albertsons.com/oauth2/...
//
// net_error -202 is ERR_CERT_AUTHORITY_INVALID. react-native-webview blocks on
// SSL errors with no override, so the navigation is cancelled before it ever
// commits and every downstream symptom follows from that: the OAuth hand-off
// after a correct MFA code cannot run, no cookie is ever set on the auth host,
// and the user is returned to the storefront still signed out. It reproduced on
// a WebView stripped to javaScriptEnabled + domStorageEnabled, so it is not
// anything the app configures.
//
// WHAT THIS IS NOT. It does not disable certificate validation and it does not
// trust anything by hostname. It adds ONE named, publicly-trusted root — the
// same certificate, by SHA-256 fingerprint, that the device already carries in
// its Conscrypt store and that Chrome already trusts:
//
//   7B:B6:47:A6:2A:EE:AC:88:BF:25:7A:A5:22:D0:1F:FE:A3:95:E0:AB:45:C7:3F:93:
//   F6:56:54:EC:38:F2:5A:06
//
// `<certificates src="system"/>` stays first, so every other host validates
// exactly as before; this only widens the anchor set by that one root.
//
// WHEN TO REMOVE IT. Once the minimum supported Android version ships this root
// in the store WebView actually consults, this is dead weight. Re-check by
// loading ciam.albertsons.com in a plain WebView on the oldest device we
// support: if it loads without this plugin, delete the plugin and the .pem.
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const CERT_SRC = 'assets/certs/sectigo-public-server-auth-root-r46.pem';
const RAW_NAME = 'sectigo_public_server_auth_root_r46';

// A network security config REPLACES the platform default for the whole app,
// including the `android:usesCleartextTraffic` the debug manifest sets so the
// dev client can reach Metro over plain HTTP. Writing one file into src/main
// would therefore silently kill every dev build's connection to Metro. So the
// config is emitted per variant, each preserving what that variant does today:
// release stays cleartext-free, debug keeps the allowance it already has, and
// both gain the anchor.
const configXml = (cleartext) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withWebViewTrustAnchors.js — do not edit by hand. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="${cleartext}">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="@raw/${RAW_NAME}" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

const withCertFiles = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const androidMain = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main');

      const rawDir = path.join(androidMain, 'res', 'raw');
      fs.mkdirSync(rawDir, { recursive: true });
      const pem = fs.readFileSync(path.join(projectRoot, CERT_SRC), 'utf8');
      // A malformed or empty anchor would fail closed at runtime — every TLS
      // connection in the app — so refuse to build rather than ship that.
      if (!pem.includes('BEGIN CERTIFICATE')) {
        throw new Error(`[withWebViewTrustAnchors] ${CERT_SRC} is not a PEM certificate`);
      }
      fs.writeFileSync(path.join(rawDir, `${RAW_NAME}.pem`), pem);

      // src/main -> release behaviour (no cleartext, as today).
      const mainXml = path.join(androidMain, 'res', 'xml');
      fs.mkdirSync(mainXml, { recursive: true });
      fs.writeFileSync(path.join(mainXml, 'network_security_config.xml'), configXml(false));

      // src/debug -> overrides the above for dev builds, keeping Metro reachable.
      const debugRes = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'debug', 'res');
      const debugXml = path.join(debugRes, 'xml');
      const debugRaw = path.join(debugRes, 'raw');
      fs.mkdirSync(debugXml, { recursive: true });
      fs.mkdirSync(debugRaw, { recursive: true });
      fs.writeFileSync(path.join(debugXml, 'network_security_config.xml'), configXml(true));
      fs.writeFileSync(path.join(debugRaw, `${RAW_NAME}.pem`), pem);

      return cfg;
    },
  ]);

const withManifestReference = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    return cfg;
  });

module.exports = (config) => withManifestReference(withCertFiles(config));
// Exported for tests: emitting cleartextTrafficPermitted="false" into src/main
// WITHOUT the debug override silently severs every dev build from Metro, which
// is a much louder failure than the one this plugin exists to fix.
module.exports.configXml = configXml;
module.exports.RAW_NAME = RAW_NAME;
