// Live Wegmans test. Gated by MEALIO_RUN_LIVE_TESTS=1 (set by `npm run test:live`).
//
// Three CHECK_LOGIN_SCRIPT tests are auto-generated by buildLiveSuite. Below
// we add Wegmans-specific extra tests (cart end-to-end).

import { getScripts } from '../../src/lib/webview-scripts/wegmans';
import { buildLiveSuite } from './helpers/build-live-suite';
import { loginWegmans } from './helpers/login-wegmans';
import { logoutWegmans } from './helpers/logout-wegmans';
import { clearCartWegmans } from './helpers/clear-cart-wegmans';

buildLiveSuite({
  storeName: 'Wegmans',
  credsKey: 'wegmans',
  homepageUrl: 'https://www.wegmans.com',
  scripts: getScripts(),
  login: loginWegmans,
  logout: logoutWegmans,
  clearCart: clearCartWegmans,
  extraTests: (ctx) => {
    describe('add-to-cart end-to-end', () => {
      it('adds 2 of Wegmans Sour Cream and the cart count goes +2', async () => {
        const page = ctx.getPage();
        const creds = ctx.getCreds();
        await loginWegmans(page, creds);

        const startCount = await getCartCount(page);

        await page.goto('https://www.wegmans.com/shop/search?query=wegmans%20sour%20cream', {
          waitUntil: 'domcontentloaded',
        });
        await page.waitForSelector('div.component--product-tile', { timeout: 20_000 });

        const session = await ctx.installBridge();
        const script = ctx.getScripts().buildSearchAndAddScript('Wegmans Sour Cream', 2, null);
        await session.inject(script);

        const result = await session.waitForMessage('SEARCH_AND_ADD_RESULT', 30_000);
        expect(result.success).toBe(true);

        await page.waitForTimeout(2000); // settle cart API
        const endCount = await getCartCount(page);
        expect(endCount).toBe(startCount + 2);
      });
    });
  },
});

async function getCartCount(page: import('playwright').Page): Promise<number> {
  const link = page.locator(
    'a[aria-label*="selected items in my Cart"], a[aria-label*="selected items in my List"]',
  ).first();
  if ((await link.count()) === 0) return 0;
  const aria = (await link.getAttribute('aria-label')) || '';
  const m = aria.match(/View (\d+) selected items/);
  return m ? parseInt(m[1], 10) : 0;
}
